apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  replicas: 3
  template:
    metadata:
      name: pod-nginx
      labels:
        app: pod-nginx
    spec:
      containers:
      - name: nginx-conatainer
        image: nginx:1
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: pod-nginx        
