apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db-noticias
spec:
  replicas: 1
  template:
    metadata:
      name: pod-db-noticias
      labels:
        app: pod-db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports: 
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: configmap-db-noticias
  selector:
    matchLabels:
      app: pod-db-noticias                