apiVersion: v1
kind: Pod
metadata:
  name: pod-db-noticias
  labels:
    app: pod-db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports: 
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: configmap-db-noticias