apiVersion: v1
kind: Pod
metadata:
  name: pod-portal-noticias
  labels:
    app: pod-portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports: 
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: configmap-portal-noticias